### ISSUE TITLE
suggest to change component name

### ISSUE THREAD

**Issue by rdlabo** [stripe-elements/stripe-elements#12]
- stripe-payment-sheet → stripe-payment
- stripe-payment-modal → stripe-sheet
- stripe-payment-sheet-modal → stripe-payment-sheet

**Comment by hideokamoto** [comment]
I'm not sure about the Stencil build specification, so I worried about the renaming effect.

@rdlabo 
Should we replace the name in its entirety files? (directory name / file name / component / name etc..)
or just replace the component name?

**Comment by rdlabo** [comment]
@hideokamoto You should change only `tag` in Components Decorator. Thanks.

**Comment by hideokamoto** [comment]
Breaking change/component name #17
