### ISSUE TITLE
return Elements name change to `**Element`

### ISSUE THREAD

**Issue by rdlabo** [stripe-elements/stripe-elements#19]
```ts
FormSubmitEvent = {
  stripe: Stripe;
  cardNumber: StripeCardNumberElement;
  cardExpiry: StripeCardExpiryElement;
  cardCVC: StripeCardCvcElement;
  intentClientSecret?: string;
};
```

```ts
const {
  detail: { stripe, cardNumber },
} = props as { :
  detail: FormSubmitEvent;
};
```

We expect cardNumber is number, and so on. So this should change to `**Element` : example `cardNumberElement`

**Comment by hideokamoto** [comment]
https://github.com/stripe-elements/stripe-elements/commit/82f86ad53344e11c9dabee23bc5d9a9a0e43f637

**Comment by hideokamoto** [comment]
https://github.com/stripe-elements/stripe-elements/releases/tag/v1.0.0-canary.0
