### ISSUE TITLE
feat(): add labelType to paymentSheet

### ISSUE THREAD

**Issue by rdlabo** [stripe-elements/stripe-elements#20]
at iOS or Android: https://github.com/capacitor-community/stripe#screenshots

PaymentSheet:
- "Add your payment information"(Android)
- "Add your payment information"(iOS)
- "Pay"

PaymentFlow:
- "Add your payment information"(Android)
- "Add a card"(iOS)
- "Add"(Android)
- "Add card"(iOS)

We should add `labelType` or `paymentType`, and judge iOS or Android.

Thanks.

**Comment by hideokamoto** [comment]
Could you describe it in more detail?
What property do you want to expect the attribute to?
Or share the use-case as a code.

@rdlabo

**Comment by rdlabo** [comment]
This is about Title, and Label of payment button:

![payment-flow-android](https://user-images.githubusercontent.com/9690024/133452262-eea85681-7870-47f0-ae1f-c65957ed0f5a.png)

I think it would be great if web design could follow natives.

**Comment by hideokamoto** [comment]
How about the `title` and `buttonLabel` attribute instead?

**Comment by hideokamoto** [comment]
Now we have no plan to support both way by default.

- PaymentSheet
- PaymentFlow

So you can customize the title and button label as an attribute.

@rdlabo

**Comment by hideokamoto** [comment]
I and @rdlabo talk about the idea.
And here is the specification we decided.

- Sheet title: `sheet-title` attribute
- Button label: `button-label` attribute
- Both OS default text should be ready to translate.
- We can put another text to these atts, but will not translate inside the component.

**Comment by hideokamoto** [comment]
https://github.com/stripe-elements/stripe-elements/releases/tag/v1.0.0-canary.0
